apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-annotations-agqz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-annotations-agqz
    app.kubernetes.io/part-of: test-annotations-app-tgys
  name: test-annotations-agqz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: test-annotations-agqz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: test-annotations-agqz
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-wfed-tenant/test-annotations-app-tgys/test-annotations-agqz@sha256:8eb8086a8a16eaaf2fb22011c1bdc13bcaf53f7bdae0598cf94872ab136fb257
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
